pref("autopager.enabled", true);
pref("autopager.debug", false);
pref("autopager.showpagehold", false);
pref("autopager.myname", "");
pref("autopager.smartenable", false);
pref("autopager.flashIconNotify", false);
pref("autopager.smarttext", "next|>|下一页|次を表示");
//refer to http://www.teesoft.info/phpbb/viewtopic.php?t=330 fro "NEXT" in Different Languages
pref("autopager.discoverytext", "navbar|right_arrow|pagN|page|pages|paging|下页|次页|Volgende|Volg|Verder|Напред|Следва|Næste|Nächste|Naechste|Weiter|Vorwärts|Vorwaerts|Volgende|Continue|Onward|Venonta|Seuraava|Suivant|Prochaine|Επόμενη|Næst|Successive|Successiva|Successivo|Prossima|Prossime|Prossimo|Altra|Altro|次へ|다음|Neste|Dalej|Następna|Następne|Następny|Więcej|Próximo|Înainte|Înaintare|Următor|Următoare|След|Следующая|Siguiente|Próxima|Próximos|Nästa|Sonraki|Devam|İlerle");
pref("autopager.smartlinks", "2");
pref("autopager.smartMargin", "1");
pref("autopager.alwaysEnableJavaScript", false);

pref("autopager.enablehotkeys.ctrlkey", true);
pref("autopager.enablehotkeys.altkey", true);
pref("autopager.enablehotkeys.shiftkey", false);
pref("autopager.loading", "position: fixed; z-index: 2147483647; font-size: 12px; bottom: 1px; max-width:160px;max-height:20px;right: 20px;padding: 1px; background: green none repeat scroll 0%; display:none;");
pref("autopager.optionstyle", "line-height:normal;width:200px;position: fixed; z-index: 2147483647; font-size: 12px; bottom: 1px; right: 20px;padding: 1px; background: green none repeat scroll 0%; display:none;text-align:left !important;");

pref("autopager.pagebreak", "clear:both; line-height:20px; background:#E6E6E6; text-align:center;margin-top:20px;margin-bottom:20px;");
pref("autopager.timeout", "120");
pref("autopager.update", "48");
pref("autopager.settingupdatedate", "");
pref("autopager.noprompt", false);
pref("autopager.modalprompt", true);
pref("autopager.disable-by-default", false);
pref("extensions.autopager@mozilla.org.description", "chrome://autopager/locale/autopager.properties");
pref("autopager.hide-status", false);
pref("autopager.hide-toolbar-icon", false);
pref("autopager.hide-context-menu", false);

pref("autopager.loadingDelayMiliseconds", "100");
pref("autopager.show-help", false);
pref("autopager.miniheight", "0.5");
pref("autopager.defaultheight", "1");
pref("autopager.minipages", "1");
pref("autopager.simulateMouseDown",false);
pref("autopager.show-workshop-in-sidebar",true);
pref("autopager.tweaking-workshop-result-style",false);
pref("autopager.show-nav-up",true);
pref("autopager.show-nav-down",true);
pref("autopager.show-nav-top",true);
pref("autopager.show-nav-bottom",true);
pref("autopager.tweaking-session",false);
pref("autopager.show-rulecount",true);
pref("autopager.include-unsafe-rules",false);
pref("autopager.mini-window-width", "200");
pref("autopager.mini-window-height", "100");
pref("autopager.set-x-autopager-httphead", false);
pref("autopager.ignore-format-version-check", false);
pref("autopager.anti-anti-autopager", false);
pref("autopager.work-in-lite-mode", false);
pref("autopager.with-lite-rules", false);
pref("autopager.with-lite-discovery", false);
pref("autopager.hide-lite-discovery-on-no-rules", true);
pref("autopager.ids", "");
pref("autopager.with-lite-recommended-rules", true);
pref("autopager.with-lite-discovery-aways-display", false);
pref("autopager.lite-discovery-prompted", false);
pref("autopager.images-prefix", "chrome://autopagerimg/content/");
pref("autopager.repository-site","http://ap.teesoft.info/");