#include "nsISupports.idl"
#include "nsIASN1Sequence.idl"

[scriptable, uuid(93AFF2EE-79AA-11DD-8660-026156D89593)]
interface nsIAutopagerCOMP : nsISupports
{
  nsIMutableArray loadAll();
  void setAll(in nsIMutableArray setting);
  nsIMutableArray getUpdateSites();
  void setUpdateSites(in nsIMutableArray sites);
  nsIMutableArray getSiteConfirms();
  void setSiteConfirms(in nsIMutableArray sites);
  nsIMutableArray getDiscoveredUrls();
  void setPublishingSite(in nsISupports site);
  nsISupports getPublishingSite();
};
